- name: Installer Docker
  apt:
    name: [docker.io]
    state: present
    update_cache: yes

- name: Ajouter deployer au groupe docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Activer et démarrer Docker
  systemd:
    name: docker
    enabled: yes
    state: started

