- name: Créer le groupe deployer
  group:
    name: deployer
    state: present

- name: Créer l'utilisateur deployer
  user:
    name: deployer
    group: deployer
    shell: /bin/bash
    createhome: yes
    state: present



